name: Pull Request Pipeline

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Lint check
        run: npm run eslint
  publish_preview:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - name: 🏗 Setup Repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Publish preview
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: 👷 Create preview comment
        uses: expo/expo-github-action/preview-comment@v7
        id: preview
        with:
          comment: false
          channel: production
      - name: Comment about success in Discord
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with: 
          severity: info
          details: 'New deployment is ready! - Preview: ${{ steps.preview.outputs.projectQR }}'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Comment about failure in Discord
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with: 
          severity: error
          details: 'Publishing of Preview failed - Go to github to re-run the failed!'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

